### ISSUE TITLE
lcmtypes ecosystem design discussion

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/lcmtypes#3]
The Drake project created this fork of https://github.com/openhumanoids/bot_core_lcmtypes for two principal reasons:
1. We want to provide shared protocol messages as a bottom-layer repo, which is depended on by many other projects, and does not depend on anything itself.  In particular, we want to simplify the dependency web between Drake, Director, and Openhumanoids.
2. We want to be able to make changes (particularly, add new messages, and modernize the build system) without placing demands on openhumanoids.

Protocol divergence between Drake and other projects is _not_ a goal.  It will be easiest to avoid if other projects adopt this repo as an external, but even if they don't, we'll do our best to avoid it by holding the forked messages identical.

I've created this thread to separate discussion of the ecosystem strategy from the copyright and licensing discussion on #2.

@wxmerkt @mwoehlke-kitware @RussTedrake @mauricefallon @rdeits

**Comment by david-german-tri** [comment]
Important fact from @ashuang on #2: 

```
LCM fingerprint is invariant to changes in package name and type name.
e.g., the following have identical fingerprints and wire format:

package abc;
struct vec2d {
  double x;
  double y;
}

package def;
struct point2d {
  double x;
  double y;
}
```

So, the namespace change in #1 did not cost us wire compatibility.

**Comment by patmarion** [comment]
I'm definitely in favor of a common and standalone repo to collect all our favorite and most useful lcm types.

I believe principal reason 1, as stated in the original comment, was the exact motivation for creating the bot_core_lcmtypes repo.  That repo collected the bot_core lcm types along with several of the types that were developed during the DRC project.

Perhaps one of the problems was the repo name, bot_core_lcmtypes, implied it was still part of the libbot library and project.  Perhaps the name bot_core part of the name should have been changed.  But the intent was likely to keep the package name bot_core, so that it would be backward compatible with c++ code and python code that import the types by name.  Of course, the name does not affect the LCM transmission compatibility.

Considering the Director code base, (and not the whole oh-distro codebase), I would be ok to adopt this new repo, robotlocotiom/lcmtypes, and update the code in director to account for the new package name.

But in this case, the existing message definitions must never be changed going forward, until all projects (oh-distro, primarily) have agreed to adopt this repo.  In the meantime, in order to change a message definition, I would propose a strict rule that you must copy and rename the type, then make your changes in the newly created type.

**Comment by david-german-tri** [comment]
> In the meantime, in order to change a message definition, I would propose a strict rule that you must copy and rename the type, then make your changes in the newly created type.

Seems reasonable to me.  We should add comments in all the messages to which this rule applies.

**Comment by mauricefallon** [comment]
The convention in ROS-land is that core ROS msg types are not managed by one group but rather are (1) jointly agreed upon and managed by the usergroup using 'REPs' (2) broken up into a few packages (sensors, geometry, nav) (3) type changes are avoided there after.

(I don't care much about all the CMake stuff as long as the wire protocol holds)

The question then is if TRI sees any role in community building or if they reserve the right to make arbitrary braking changes as is currently the case. (@mwoehlke-kitware 's comments on the other issue were not particularly reassuring)

Personally, I think it should be straightforward for TRI to use a set of independently/community maintained types - especially for core aspects such as sensor data. (I'd be happy for TRI to modernise CMake as they feel. New Drake specific types should be added to a different repo)

**Comment by mauricefallon** [comment]
(PS: @patmarion 's comments regarding the name bot_core_lcmtypes are correct. That was my intention)

**Comment by liangfok** [comment]
Can we also adopt a convention where message names and file names include a version number? For example, `gps_data_t_v1.lcm` would contain a `struct gps_data_t_v1`?

**Comment by david-german-tri** [comment]
@mauricefallon, just to be clear, you asked us to fork: https://github.com/openhumanoids/bot_core_lcmtypes/pull/18#issuecomment-224004134

> The question then is if TRI sees any role in community building or if they reserve the right to make arbitrary braking changes as is currently the case. (@mwoehlke-kitware 's comments on the other issue were not particularly reassuring)

Let me try to be more specific about our plans. Here is the exact set of steps that @RussTedrake has approved:
- Resolve https://github.com/RobotLocomotion/drake/issues/3344 by 
  moving mwoehlke-kitware's fork of bot_core_lcmtypes into 
  RobotLocomotion/lcmtypes
- Copy in items from drc_lcmtypes which we need
- Change director to use types from bot_core_lcmtypes [meaning RobotLocomotion/lcmtypes]

None of those steps breaks wire compatibility, to the best of my knowledge.  If I'm wrong about that we should rethink.

**Comment by mauricefallon** [comment]
That's fine @david-german-tri . It seems to be something we could work with.

What I am suggesting is that instead of RL/lcmtypes, something more neutral would be preferred. 

I also don't think its scalable to just dump in what ever new types we or TRI come up with. There a quite a number of them already. Hence the suggestion to break up types by function as in ROS

BTW: I don't agree with @liangfok about supporting versions of types. Where types have been properly designed, changes shouldn't be needed. Where changes really are needed, then the change should be made with git history keeping the version. A proper versioning mechanism doesn't exist in LCM.

**Comment by liangfok** [comment]
OK. I suppose the name itself can be made more expressive, like `gps_data_t_global_top_fgpmmopa6h.lcm`. :smile:

**Comment by david-german-tri** [comment]
> What I am suggesting is that instead of RL/lcmtypes, something more neutral would be preferred.

The entity with ownership bits needs to have the resources to act on PRs in a timely fashion.  I'm open to alternative solutions subject to that constraint.

> I also don't think its scalable to just dump in what ever new types we or TRI come up with. There a quite a number of them already. Hence the suggestion to break up types by function as in ROS

As stated above, our design goal is only to house shared types here.  Drake-only types should live in Drake.  OH-only types should live in OH.  If the number of shared types becomes massive, I agree it makes sense to look at a tree of folders.  If it becomes really massive, perhaps a tree of repositories.  But we're not there yet.

**Comment by mwoehlke-kitware** [comment]
> The question then is if TRI sees any role in community building or if they reserve the right to make arbitrary braking changes as is currently the case. (@mwoehlke-kitware 's comments on the other issue were not particularly reassuring)

Yes, sorry for that. Let me try to clarify; echoing David's latest comment, we need the ability to have fast turn-around _at a repository level_. This can reflect tasks such as adding new types (or changing recently added types that are still "in flux") or making build system changes. Both of these are specific issues that have come up and led to the creation of this repository. But that does _not_ imply we need to gratuitously change the wire format of _established_ types. I think we all agree we'd like to avoid that if possible.

**Comment by patmarion** [comment]
I can describe how this will look on a technical level, but I do not want to suggest that the discussion is finished.  Part of the original motivation for the fork may have been that I was not present to help resolve build issues back in June.  Now I am back and willing to help.

@mauricefallon makes a point about organizing message collections by function.  The messages in bot_core_lcmtypes are a good collection.  Robotlocomotion/lcmtypes combines this collection with "in flux" messages, such as the drake drawing API.

I can update drake-visualizer to use robotlocomotion/lcmtypes.  Director will continue to use bot_core_lcmtypes elsewhere in its codebase.  Robotlocomotion/lcmtypes can be added to the drake superbuild and bot_core_lcmtypes removed.

We can add robotlocomotion/lcmtypes to the oh-distro superbuild.  It compiles successfully and will not interrupt build stability.  Code in oh-distro can continue using bot_core_lcmtypes, or transition to robotlocomotion/lcmtypes, both would be available and there would not be name clashes.  But there cannot be divergence in message definitions for forked messages shared by both repos.

Alternatively, bot_core_lcmtypes can accept the cmake modernization pull request, and Drake can continue to use bot_core_lcmtypes.  Drake can still push new messages to robotlocomotion/lcmtypes, and as the messages mature then perhaps some will migrate to bot_core_lcmtypes.  I personally am in favor of this option, and merging https://github.com/openhumanoids/bot_core_lcmtypes/pull/20

**Comment by mauricefallon** [comment]
I agree with what Pat is requesting above (at the end). Which I summarise as:
- drake continues to use bot_core types but keeps (only) drake-specific types in RL/lcmtypes
- remove drake-visualiser types from bot_core
- upgrade bot_core types to use new cmake build
- avoid bloating bot_core types with new types going forward

Could we work on some form of 'policy' for this?

(Keen to resolve this so we can move on)

**Comment by sammy-tri** [comment]
My primary interest was/is in being able to more easily share types between Drake/director/openhumanoids.  Maybe I screwed up here in trying to combine this goal with @mwoehlke-kitware's cmake updates, though it seems reasonable at the time.

I don't think anyone at TRI wants to make breaking changes to established types.  If it would be easier to work with the OH community by keeping the items in bot_core_lcmtypes exactly as they are (not even a package name change), then we can restart this repo from scratch with just the stuff I wanted out of drc_lcmtypes in OH.

Of course, I'd probably end up changing the package name on those too, and then director would use the new package name, and then we'd be in the same place we are now.  Or am I missing something?

**Comment by patmarion** [comment]
I agree, I would like a stand alone repo with robot plan messages etc so that drake and director can run standalone to do useful things with robot urdf and ik plans.  So what about these steps:
- merge the cmake modernization pull request in bot_core_lcmtypes
- keep this repo, but remove the types forked from bot_core_lcmtypes
- oh-distro adopts this repo so that director can import types from this repo under the new package name
- code in oh-distro can migrate to the new package name at a slower pace

**Comment by mwoehlke-kitware** [comment]
> Drake can still push new messages to robotlocomotion/lcmtypes, and as the messages mature then perhaps some will migrate to bot_core_lcmtypes

As noted, one gripe I have with that is that types are being added to a repository that is _not_ libbot but are being represented as if they were. One of the reasons for #1's rebranding was to address this issue.

If we go back to OH hosting a primary repo, I'd like to request that we rename it to something other than bot_core_types, and make a similar package name change for at least those types that did not come from libbot. Or else agree (specifically, I would want at least @ashuang's buy-in¹) to move the repo "back" to the libbot organization.

(¹ In terms of the set of types; I'm pretty sure he's fine having an LCM types repo in libbot.)

**Comment by patmarion** [comment]
I agree with your point about the branding confusion.  I mentioned it earlier as well.  However, I propose we drop that point from the discussion so we can move forward right now.

**Comment by mauricefallon** [comment]
@mwoehlke-kitware : The reason for avoiding rebranding bot_core as that it unnecessarily requires changes to lots of code developed over years which is working well as is. I'm not in favour of change for change sake. The branding is not important.
- libbot is essentially a minimally maintained historical project.
- bot_core_lcmtypes are more important as its types are the interface between all our modules.

But I would be happy to move bot_core_lcmtypes to a neutral organization where we could jointly manage it. I just felt that OH was that place.

**Comment by david-german-tri** [comment]
@patmarion's steps in https://github.com/RobotLocomotion/lcmtypes/issues/3#issuecomment-252654749 sound like a consensus.  We can mull renaming `bot_core_lcmtypes` as a separate step, but I am inclined to agree with @mauricefallon that it's not worth the churn.

I do have two additional requests from earlier in the thread:
- Now that you all have agreed to license the existing content of `bot_core_lcmtypes` as BSD 3-clause on #2 (thanks!), can that become the license for `bot_core_lcmtypes` going forward, with appropriate `LICENSE` and `COPYRIGHT` files?
- @mauricefallon, If we're going to jointly manage bot_core_lcmtypes, we need to agree on a protocol for PR review that doesn't block the Drake universe on limited OH resources.  Would you accept the Drake PR process for any changes that you don't have time to review yourself?  That would mean giving the Drake platform reviewers write access, which we would promise only to use on the changes you decline to review.  I think we will rarely PR to it at all (the build cleanup is a one-time thing), but I don't want to replay this whole thread a few months or years down the line.

**Comment by mauricefallon** [comment]
We've now [accepted the CMake updates for bot_core_lcmtypes](https://github.com/openhumanoids/bot_core_lcmtypes/pull/20#issuecomment-253157662)
- I think we now agree not to change the name of bot_core_lcmtypes

@david-german-tri : I'm happy give you guys permissions and benign control of bot_core_lcmtypes. My understanding is that future changes to it will be minor and that drake specific lcmtypes will not be added to it.

OpenHumanoids is a bad organisation name. We should have chosen a neutral name e.g. "robust robots" or "dynamic robots" for shared LCM tools

**Comment by sammy-tri** [comment]
Ok, I guess we move forward on @patmarion suggestion that we only put the lcmtypes which he and I immediately care about for director/IK stuff in this repo.  So it sounds like the needed changes include (at least): 
- Update our CMake foo (merge #4)
- Delete all of the existing types
- Add a dependency on bot_core_lcmtypes
- Add new types (which need the bot_core_lcmtypes dependency)
- Add Drake external for this repo

Sound about right?

**Comment by patmarion** [comment]
Yes, sounds great.  Are you volunteering for this?

**Comment by sammy-tri** [comment]
Some assistance from @mwoehlke-kitware on getting the bot_core_lcmtypes dependency right in CMake might be needed (I haven't looked at it, so don't know how hard that'll be)...  Otherwise I'll volunteer.

**Comment by mwoehlke-kitware** [comment]
> So it sounds like the needed changes include [...] Delete all of the existing types

At that point, you might as well start a new history. Why carry around the history of effectively an entirely different repository?

> Some assistance from @mwoehlke-kitware on getting the bot_core_lcmtypes dependency right in CMake might be needed

This is probably all you need:

``` cmake
find_package(bot2-core REQUIRED)

target_link_libraries(robotlocomotion-lcmtypes PUBLIC lcmtypes_bot2-core)
target_link_libraries(robotlocomotion-lcmtypes-cpp PUBLIC lcmtypes_bot2-core-cpp)
```

...but do the proposed types include OH types? If not, is the dependency even needed?

(I still think we _really_ should rename the upstream project to something more sensible. If nothing else, I'd like to see naming conventions normalized.)

**Comment by mwoehlke-kitware** [comment]
> This is probably all you need:

Note: each of those lines should go in different places, not consecutively :smile:. The `find_package` should be in the root `CMakeLists.txt` and the `target_link_libraries` should go with the other bits for their respective libraries.

**Comment by sammy-tri** [comment]
Agreed about smashing the history.  I'm still going to merge #4 first so I at least have up to date make rules.

The proposed types are coming from OH, and definitely have bot_core dependencies, which is (I think) part of the reason it made sense to me to move them into there in the first place. 

So current plan is more like:
- Merge #4 
- Copy over at least one type from OH so we know the build works (maybe just all of the once needed for robot_plan_t in the first wave) and update the dependencies
- Squash history so that's the starting point of this repo.
- Add new types (or other fixes) by PR as needed after that.

**Comment by patmarion** [comment]
and also the drake viewer messages, right?

**Comment by mauricefallon** [comment]
So bot_core will go back to being the source of  planar_lidar_t and image_t, joint_state_t? (+1 from me)

BTW, I think robot_plan_t should be redesigned. It contains about 6 other dependent types and a bunch of junk within it e.g.:
- robot_state_t, grasp_transition_state_t (as well as their dependents)
- matlab_data, grasps, plan_info

I heavily recommend against making types which are dependent on simple data structures:
- for example bot_core_vector_3d_t.lcm contains 3 doubles, which is silly.

**Comment by patmarion** [comment]
+1 for revisiting the design of plan messages.  I think we can do that over time though, and I am happy to port the messages over asap in their current form, then tweak them in place there.

Director only access a few attributes of the plan messages and ignores all the legacy attributes, so it should be forward compatible if the legacy attributes are removed.  If the useful attributes are also to be renamed, then I'll make sure Director is compatible with old-style and new-style, because playback of old logs is important to me.

Let's have a separate discussion for plan message redesign, I think there could be a lot to discuss.

**Comment by mwoehlke-kitware** [comment]
> Squash history so that's the starting point of this repo.

Note that the easiest way to do this is probably `git checkout --orphan new_history`.

**Comment by sammy-tri** [comment]
Since we're going to squash the history anyway, I've gone ahead and made the current master branch look like what I'm thinking would be a good starting point.  It builds in a branch of Drake for me and includes the types I needed from OH to send a plan from director to Drake.  If we agree that this basically meets the vision for this repo going forward, I'll squash history and switch to using PRs after that (instead of directly mangling the repo myself).

Thanks all for the feedback!

**Comment by patmarion** [comment]
Looks good to me.

I would also be in favor of moving the lcmt_viewer_*.lcm messages from drake/lcmtypes into this repository, and removing the forked copies of those messages that @rdeits added to bot_core_lcmtypes.  Then the viewer messages will exist only in this repo.

**Comment by rdeits** [comment]
Yup, @patmarion that's fine by me.

**Comment by sammy-tri** [comment]
No objection to moving the viewer messages, though I think I'm going to wait on it a bit until I've got this repo squashed (and possible integrated with Drake) and then we can PR in that change.  Assuming the other interested parties are also OK with the current layout, I'll squash tomorrow and hopefully PR into Drake not long after.

**Comment by sammy-tri** [comment]
It turns out I don't have the bits to rewrite history on the master branch.  Will coordinate with @RussTedrake and notify here once master has the appropriate history.  I believe that to be the final issue before closing this ticket.

**Comment by sammy-tri** [comment]
History has been rewritten.  Closing.
